pipeline {
    agent any

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main', url: 'https://github.com/Mtiukin-Vlad/Hillel_aqa_python'
            }
        }

        stage('Install env') {
           steps {
                sh '''
                apt-get update
                apt-get install -y python3 python3-dev python3-pip python3.11-venv
                rm -rf .venv
               '''
            }
        }

        stage('Install dependencies') {
              steps {
                sh '''
                  python3 -m venv .venv
                  . .venv/bin/activate
                  cd lesson_10
                  pip install -r requirements.txt
               '''
            }
        }

        stage('Run tests') {
            steps {
                  sh '''
                     . .venv/bin/activate
                     cd lesson_10
                     pytest
                  '''
            }
        }
    }

     post {
        success {
            mail to: 'vladlen1213@gmail.com',
                 subject: "Тести пройдено: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Усі тести пройдено успішно\n${env.BUILD_URL}"
        }
        failure {
            mail to: 'vladlen1213@gmail.com',
                 subject: "Помилка тестів: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Тести завершилися з помилкою\n${env.BUILD_URL}"
        }
    }
}
